apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: payment-router-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: payment-router
  minReplicas: 6
  maxReplicas: 200
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 15
      policies:
        - type: Pods
          value: 20
          periodSeconds: 30
    scaleDown:
      stabilizationWindowSeconds: 300
